name: Pygmalion UI Front End - Build / Quality Control

permissions:
  contents: read # This is required for actions/checkout

on:
  workflow_dispatch:   # Allows you to run this workflow manually from the Actions tab

jobs:       
  dependencies:
    name: Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Performant Node Package Manager (NPM)
        uses: pnpm/action-setup@v2
        with:
          version: 7.2.1

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.4.0'

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
  
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Quality Control - Lint
        run: pnpm run lint
        
  style:
    name: style
    runs-on: ubuntu-latest
    steps:
      - name: Quality Control - Style
        run: pnpm run style
        
  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Quality Control - TypeCheck
        run: pnpm run typecheck
