name: Pygmalion UI Front End - Build / Quality Control

permissions:
  # This is required for actions/checkout
  contents: read 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:   

env:
  node-version: '18.4.0'
  pnpm-version: 7.2.1

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies - Composite Action
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Get Previously Cache Dependencies
        # cache is automatically saved after this job completes. jobs depending on this one will get the latest cached files
        id: cache-step
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies (unless restored from cache)
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        
  lint:
    name: Lint
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies - Composite Action
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Restore Cache - Composite Action
        uses: ./.github/actions/restore-pnpm-cache

      - name: Quality Control - Lint
        run: pnpm run lint
        
  style:
    name: Style
    needs: dependencies
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies - Composite Action
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Restore Cache - Composite Action
        uses: ./.github/actions/restore-pnpm-cache
          
      - name: Quality Control - Style
        run: pnpm run style
          
  typecheck:
    name: TypeCheck
    needs: dependencies
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies - Composite Action
        uses: ./.github/actions/install-node-pnpm
        with:
          node-version: ${{  env.node-version  }}
          pnpm-version: ${{  env.pnpm-version  }}

      - name: Restore Cache - Composite Action
        uses: ./.github/actions/restore-pnpm-cache
          
      - name: Quality Control - TypeCheck
        run: pnpm run typecheck
