name: Pygmalion UI Front End - Build / Quality Control

permissions:
  # This is required for actions/checkout
  contents: read 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:   

env:
  node-version: '18.4.0'
  pnpm-version: 7.2.1

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Performant Node Package Manager (NPM)
        uses: pnpm/action-setup@v2
        with:
          version: ${{  env.pnpm-version  }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{  env.node-version  }}

      - name: Get Previously Cache Dependencies
        id: cache-step
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies (unless restored from cache)
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile
        
  lint:
    name: Lint
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
    
      - name: Install Performant Node Package Manager (NPM)
        uses: pnpm/action-setup@v2
        with:
          version: ${{  env.pnpm-version  }}
    
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true

      - name: Quality Control - Lint
        run: pnpm run lint
        
  style:
    name: Style
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
    
      - name: Install Performant Node Package Manager (NPM)
        uses: pnpm/action-setup@v2
        with:
          version: ${{  env.pnpm-version  }}
    
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true
          
      - name: Quality Control - Style
        run: pnpm run style
          
    typecheck:
    name: TypeCheck
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
    
      - name: Install Performant Node Package Manager (NPM)
        uses: pnpm/action-setup@v2
        with:
          version: ${{  env.pnpm-version  }}
    
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          fail-on-cache-miss: true
          
      - name: Quality Control - TypeCheck
        run: pnpm run typecheck
